[book]
authors = ["Hsiang-Jui Lin <jerry73204@gmail.com>"]
language = "zh-TW"
multilingual = false
src = "src"
title = "AutoSDV 手冊"

[preprocessor.gettext]
po-file = "po/zh-TW.po"

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/NEWSLabNTU/AutoSDV-book"
edit-url-template = "https://github.com/NEWSLabNTU/AutoSDV-book/edit/main/{path}"