[book]
authors = ["Hsiang-Jui Lin <jerry73204@gmail.com>"]
language = "en"
src = "src"
title = "AutoSDV Book"

[preprocessor.gettext]

[output.html]
default-theme = "light"
preferred-dark-theme = "navy"
git-repository-url = "https://github.com/NEWSLabNTU/AutoSDV-book"
edit-url-template = "https://github.com/NEWSLabNTU/AutoSDV-book/edit/main/{path}"